services:
  postgresd:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", -U, kratos]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kratos_intranet

  hydra:
    image: oryd/hydra:v2.2.0
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user

    # ╭──────────────────────────────────────────────────────────╮
    # │command: in prod should not use flag `--dev`              │
    # ╰──────────────────────────────────────────────────────────╯
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - type: bind
        source: ./config
        target: /etc/config/hydra
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - kratos_intranet
  hydra-migrate:
    image: oryd/hydra:v2.2.0
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./contrib/quickstart/5-min
        target: /etc/config/hydra
    restart: on-failure
    networks:
      - kratos_intranet

  # ╭──────────────────────────────────────────────────────────╮
  # │ example of consent page                                  │
  # ╰──────────────────────────────────────────────────────────╯
  consent:
    environment:
      - HYDRA_ADMIN_URL=http://hydra:4445
    image: oryd/hydra-login-consent-node:v2.2.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - kratos_intranet
networks:
  kratos_intranet:
    external: true
